FROM tomsquest/docker-radicale:3.1.8.0

MAINTAINER JJGadgets <contact [at] jjgadgets.tech>

RUN set -ex \
    && python3 -m pip install --upgrade git+https://github.com/pvagner/radicale-auth-ldap.git@3
